USE [master]
GO

/****** Object:  Database [SLS]    Script Date: 2014-10-23 15:17:03 ******/
DROP DATABASE [SLS]
GO

/****** Object:  Database [SLS]    Script Date: 2014-10-23 15:17:03 ******/
CREATE DATABASE [SLS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SLS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\SLS.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SLS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\SLS_log.ldf' , SIZE = 1024KB , MAXSIZE = 1024000KB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SLS] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SLS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SLS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SLS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SLS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SLS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SLS] SET ARITHABORT OFF 
GO

ALTER DATABASE [SLS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SLS] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SLS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SLS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SLS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SLS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SLS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SLS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SLS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SLS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SLS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SLS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SLS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SLS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SLS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SLS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SLS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SLS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SLS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SLS] SET  MULTI_USER 
GO

ALTER DATABASE [SLS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SLS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SLS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SLS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SLS] SET  READ_WRITE 
GO

