//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLS.Desktop.SLSDesktopServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/SLS.WCFService")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int available_copiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string coverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string isbnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string languageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string publish_cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> publish_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> publish_editionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string table_of_contentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int available_copies {
            get {
                return this.available_copiesField;
            }
            set {
                if ((this.available_copiesField.Equals(value) != true)) {
                    this.available_copiesField = value;
                    this.RaisePropertyChanged("available_copies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cover {
            get {
                return this.coverField;
            }
            set {
                if ((object.ReferenceEquals(this.coverField, value) != true)) {
                    this.coverField = value;
                    this.RaisePropertyChanged("cover");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string isbn {
            get {
                return this.isbnField;
            }
            set {
                if ((object.ReferenceEquals(this.isbnField, value) != true)) {
                    this.isbnField = value;
                    this.RaisePropertyChanged("isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string language {
            get {
                return this.languageField;
            }
            set {
                if ((object.ReferenceEquals(this.languageField, value) != true)) {
                    this.languageField = value;
                    this.RaisePropertyChanged("language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string publish_city {
            get {
                return this.publish_cityField;
            }
            set {
                if ((object.ReferenceEquals(this.publish_cityField, value) != true)) {
                    this.publish_cityField = value;
                    this.RaisePropertyChanged("publish_city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> publish_date {
            get {
                return this.publish_dateField;
            }
            set {
                if ((this.publish_dateField.Equals(value) != true)) {
                    this.publish_dateField = value;
                    this.RaisePropertyChanged("publish_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> publish_edition {
            get {
                return this.publish_editionField;
            }
            set {
                if ((this.publish_editionField.Equals(value) != true)) {
                    this.publish_editionField = value;
                    this.RaisePropertyChanged("publish_edition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string table_of_contents {
            get {
                return this.table_of_contentsField;
            }
            set {
                if ((object.ReferenceEquals(this.table_of_contentsField, value) != true)) {
                    this.table_of_contentsField = value;
                    this.RaisePropertyChanged("table_of_contents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/SLS.WCFService")]
    [System.SerializableAttribute()]
    public partial class BookNotFoundFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="author", Namespace="http://schemas.datacontract.org/2004/07/SLS.WCFService")]
    [System.SerializableAttribute()]
    public partial class author : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Desktop.SLSDesktopServiceProxy.book_authors[] book_authorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_of_birthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_of_deathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Desktop.SLSDesktopServiceProxy.book_authors[] book_authors {
            get {
                return this.book_authorsField;
            }
            set {
                if ((object.ReferenceEquals(this.book_authorsField, value) != true)) {
                    this.book_authorsField = value;
                    this.RaisePropertyChanged("book_authors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_of_birth {
            get {
                return this.date_of_birthField;
            }
            set {
                if ((this.date_of_birthField.Equals(value) != true)) {
                    this.date_of_birthField = value;
                    this.RaisePropertyChanged("date_of_birth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_of_death {
            get {
                return this.date_of_deathField;
            }
            set {
                if ((this.date_of_deathField.Equals(value) != true)) {
                    this.date_of_deathField = value;
                    this.RaisePropertyChanged("date_of_death");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="book_authors", Namespace="http://schemas.datacontract.org/2004/07/SLS.WCFService")]
    [System.SerializableAttribute()]
    public partial class book_authors : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Desktop.SLSDesktopServiceProxy.author authorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int author_id_fkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Desktop.SLSDesktopServiceProxy.book1 bookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int book_id_fkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Desktop.SLSDesktopServiceProxy.author author {
            get {
                return this.authorField;
            }
            set {
                if ((object.ReferenceEquals(this.authorField, value) != true)) {
                    this.authorField = value;
                    this.RaisePropertyChanged("author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int author_id_fk {
            get {
                return this.author_id_fkField;
            }
            set {
                if ((this.author_id_fkField.Equals(value) != true)) {
                    this.author_id_fkField = value;
                    this.RaisePropertyChanged("author_id_fk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Desktop.SLSDesktopServiceProxy.book1 book {
            get {
                return this.bookField;
            }
            set {
                if ((object.ReferenceEquals(this.bookField, value) != true)) {
                    this.bookField = value;
                    this.RaisePropertyChanged("book");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int book_id_fk {
            get {
                return this.book_id_fkField;
            }
            set {
                if ((this.book_id_fkField.Equals(value) != true)) {
                    this.book_id_fkField = value;
                    this.RaisePropertyChanged("book_id_fk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ord {
            get {
                return this.ordField;
            }
            set {
                if ((this.ordField.Equals(value) != true)) {
                    this.ordField = value;
                    this.RaisePropertyChanged("ord");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="book", Namespace="http://schemas.datacontract.org/2004/07/SLS.WCFService")]
    [System.SerializableAttribute()]
    public partial class book1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int available_copiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Desktop.SLSDesktopServiceProxy.book_authors[] book_authorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Desktop.SLSDesktopServiceProxy.borrow[] borrowsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Desktop.SLSDesktopServiceProxy.category[] categoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string coverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string isbnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string languageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string publish_cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> publish_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> publish_editionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Desktop.SLSDesktopServiceProxy.publisher publisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> publisher_id_fkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Desktop.SLSDesktopServiceProxy.reservation[] reservationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string table_of_contentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int available_copies {
            get {
                return this.available_copiesField;
            }
            set {
                if ((this.available_copiesField.Equals(value) != true)) {
                    this.available_copiesField = value;
                    this.RaisePropertyChanged("available_copies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Desktop.SLSDesktopServiceProxy.book_authors[] book_authors {
            get {
                return this.book_authorsField;
            }
            set {
                if ((object.ReferenceEquals(this.book_authorsField, value) != true)) {
                    this.book_authorsField = value;
                    this.RaisePropertyChanged("book_authors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Desktop.SLSDesktopServiceProxy.borrow[] borrows {
            get {
                return this.borrowsField;
            }
            set {
                if ((object.ReferenceEquals(this.borrowsField, value) != true)) {
                    this.borrowsField = value;
                    this.RaisePropertyChanged("borrows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Desktop.SLSDesktopServiceProxy.category[] categories {
            get {
                return this.categoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.categoriesField, value) != true)) {
                    this.categoriesField = value;
                    this.RaisePropertyChanged("categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cover {
            get {
                return this.coverField;
            }
            set {
                if ((object.ReferenceEquals(this.coverField, value) != true)) {
                    this.coverField = value;
                    this.RaisePropertyChanged("cover");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string isbn {
            get {
                return this.isbnField;
            }
            set {
                if ((object.ReferenceEquals(this.isbnField, value) != true)) {
                    this.isbnField = value;
                    this.RaisePropertyChanged("isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string language {
            get {
                return this.languageField;
            }
            set {
                if ((object.ReferenceEquals(this.languageField, value) != true)) {
                    this.languageField = value;
                    this.RaisePropertyChanged("language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string publish_city {
            get {
                return this.publish_cityField;
            }
            set {
                if ((object.ReferenceEquals(this.publish_cityField, value) != true)) {
                    this.publish_cityField = value;
                    this.RaisePropertyChanged("publish_city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> publish_date {
            get {
                return this.publish_dateField;
            }
            set {
                if ((this.publish_dateField.Equals(value) != true)) {
                    this.publish_dateField = value;
                    this.RaisePropertyChanged("publish_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> publish_edition {
            get {
                return this.publish_editionField;
            }
            set {
                if ((this.publish_editionField.Equals(value) != true)) {
                    this.publish_editionField = value;
                    this.RaisePropertyChanged("publish_edition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Desktop.SLSDesktopServiceProxy.publisher publisher {
            get {
                return this.publisherField;
            }
            set {
                if ((object.ReferenceEquals(this.publisherField, value) != true)) {
                    this.publisherField = value;
                    this.RaisePropertyChanged("publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> publisher_id_fk {
            get {
                return this.publisher_id_fkField;
            }
            set {
                if ((this.publisher_id_fkField.Equals(value) != true)) {
                    this.publisher_id_fkField = value;
                    this.RaisePropertyChanged("publisher_id_fk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Desktop.SLSDesktopServiceProxy.reservation[] reservations {
            get {
                return this.reservationsField;
            }
            set {
                if ((object.ReferenceEquals(this.reservationsField, value) != true)) {
                    this.reservationsField = value;
                    this.RaisePropertyChanged("reservations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string table_of_contents {
            get {
                return this.table_of_contentsField;
            }
            set {
                if ((object.ReferenceEquals(this.table_of_contentsField, value) != true)) {
                    this.table_of_contentsField = value;
                    this.RaisePropertyChanged("table_of_contents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="publisher", Namespace="http://schemas.datacontract.org/2004/07/SLS.WCFService")]
    [System.SerializableAttribute()]
    public partial class publisher : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Desktop.SLSDesktopServiceProxy.book1[] booksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Desktop.SLSDesktopServiceProxy.book1[] books {
            get {
                return this.booksField;
            }
            set {
                if ((object.ReferenceEquals(this.booksField, value) != true)) {
                    this.booksField = value;
                    this.RaisePropertyChanged("books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="borrow", Namespace="http://schemas.datacontract.org/2004/07/SLS.WCFService")]
    [System.SerializableAttribute()]
    public partial class borrow : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Desktop.SLSDesktopServiceProxy.book1 bookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int book_id_fkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime from_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int prolong_cntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime to_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Desktop.SLSDesktopServiceProxy.user userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int user_id_fkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Desktop.SLSDesktopServiceProxy.book1 book {
            get {
                return this.bookField;
            }
            set {
                if ((object.ReferenceEquals(this.bookField, value) != true)) {
                    this.bookField = value;
                    this.RaisePropertyChanged("book");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int book_id_fk {
            get {
                return this.book_id_fkField;
            }
            set {
                if ((this.book_id_fkField.Equals(value) != true)) {
                    this.book_id_fkField = value;
                    this.RaisePropertyChanged("book_id_fk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime from_date {
            get {
                return this.from_dateField;
            }
            set {
                if ((this.from_dateField.Equals(value) != true)) {
                    this.from_dateField = value;
                    this.RaisePropertyChanged("from_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int prolong_cnt {
            get {
                return this.prolong_cntField;
            }
            set {
                if ((this.prolong_cntField.Equals(value) != true)) {
                    this.prolong_cntField = value;
                    this.RaisePropertyChanged("prolong_cnt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime to_date {
            get {
                return this.to_dateField;
            }
            set {
                if ((this.to_dateField.Equals(value) != true)) {
                    this.to_dateField = value;
                    this.RaisePropertyChanged("to_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Desktop.SLSDesktopServiceProxy.user user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user_id_fk {
            get {
                return this.user_id_fkField;
            }
            set {
                if ((this.user_id_fkField.Equals(value) != true)) {
                    this.user_id_fkField = value;
                    this.RaisePropertyChanged("user_id_fk");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="category", Namespace="http://schemas.datacontract.org/2004/07/SLS.WCFService")]
    [System.SerializableAttribute()]
    public partial class category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Desktop.SLSDesktopServiceProxy.book1[] booksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Desktop.SLSDesktopServiceProxy.book1[] books {
            get {
                return this.booksField;
            }
            set {
                if ((object.ReferenceEquals(this.booksField, value) != true)) {
                    this.booksField = value;
                    this.RaisePropertyChanged("books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="reservation", Namespace="http://schemas.datacontract.org/2004/07/SLS.WCFService")]
    [System.SerializableAttribute()]
    public partial class reservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Desktop.SLSDesktopServiceProxy.book1 bookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int book_id_fkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> queue_positionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime reservation_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Desktop.SLSDesktopServiceProxy.user userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int user_id_fkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Desktop.SLSDesktopServiceProxy.book1 book {
            get {
                return this.bookField;
            }
            set {
                if ((object.ReferenceEquals(this.bookField, value) != true)) {
                    this.bookField = value;
                    this.RaisePropertyChanged("book");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int book_id_fk {
            get {
                return this.book_id_fkField;
            }
            set {
                if ((this.book_id_fkField.Equals(value) != true)) {
                    this.book_id_fkField = value;
                    this.RaisePropertyChanged("book_id_fk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> queue_position {
            get {
                return this.queue_positionField;
            }
            set {
                if ((this.queue_positionField.Equals(value) != true)) {
                    this.queue_positionField = value;
                    this.RaisePropertyChanged("queue_position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime reservation_date {
            get {
                return this.reservation_dateField;
            }
            set {
                if ((this.reservation_dateField.Equals(value) != true)) {
                    this.reservation_dateField = value;
                    this.RaisePropertyChanged("reservation_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Desktop.SLSDesktopServiceProxy.user user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user_id_fk {
            get {
                return this.user_id_fkField;
            }
            set {
                if ((this.user_id_fkField.Equals(value) != true)) {
                    this.user_id_fkField = value;
                    this.RaisePropertyChanged("user_id_fk");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="user", Namespace="http://schemas.datacontract.org/2004/07/SLS.WCFService")]
    [System.SerializableAttribute()]
    public partial class user : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Desktop.SLSDesktopServiceProxy.borrow[] borrowsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int incorrect_login_cntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string last_login_infoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Desktop.SLSDesktopServiceProxy.reservation[] reservationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Desktop.SLSDesktopServiceProxy.role roleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int role_id_fkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Desktop.SLSDesktopServiceProxy.borrow[] borrows {
            get {
                return this.borrowsField;
            }
            set {
                if ((object.ReferenceEquals(this.borrowsField, value) != true)) {
                    this.borrowsField = value;
                    this.RaisePropertyChanged("borrows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int incorrect_login_cnt {
            get {
                return this.incorrect_login_cntField;
            }
            set {
                if ((this.incorrect_login_cntField.Equals(value) != true)) {
                    this.incorrect_login_cntField = value;
                    this.RaisePropertyChanged("incorrect_login_cnt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string last_login_info {
            get {
                return this.last_login_infoField;
            }
            set {
                if ((object.ReferenceEquals(this.last_login_infoField, value) != true)) {
                    this.last_login_infoField = value;
                    this.RaisePropertyChanged("last_login_info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string passwd {
            get {
                return this.passwdField;
            }
            set {
                if ((object.ReferenceEquals(this.passwdField, value) != true)) {
                    this.passwdField = value;
                    this.RaisePropertyChanged("passwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int phone {
            get {
                return this.phoneField;
            }
            set {
                if ((this.phoneField.Equals(value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Desktop.SLSDesktopServiceProxy.reservation[] reservations {
            get {
                return this.reservationsField;
            }
            set {
                if ((object.ReferenceEquals(this.reservationsField, value) != true)) {
                    this.reservationsField = value;
                    this.RaisePropertyChanged("reservations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Desktop.SLSDesktopServiceProxy.role role {
            get {
                return this.roleField;
            }
            set {
                if ((object.ReferenceEquals(this.roleField, value) != true)) {
                    this.roleField = value;
                    this.RaisePropertyChanged("role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int role_id_fk {
            get {
                return this.role_id_fkField;
            }
            set {
                if ((this.role_id_fkField.Equals(value) != true)) {
                    this.role_id_fkField = value;
                    this.RaisePropertyChanged("role_id_fk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="role", Namespace="http://schemas.datacontract.org/2004/07/SLS.WCFService")]
    [System.SerializableAttribute()]
    public partial class role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Desktop.SLSDesktopServiceProxy.user[] usersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Desktop.SLSDesktopServiceProxy.user[] users {
            get {
                return this.usersField;
            }
            set {
                if ((object.ReferenceEquals(this.usersField, value) != true)) {
                    this.usersField = value;
                    this.RaisePropertyChanged("users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityCouldNotBeAdded", Namespace="http://schemas.datacontract.org/2004/07/SLS.WCFService")]
    [System.SerializableAttribute()]
    public partial class EntityCouldNotBeAdded : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SLSDesktopServiceProxy.ISLSDesktopService")]
    public interface ISLSDesktopService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSDesktopService/GetBook", ReplyAction="http://tempuri.org/ISLSDesktopService/GetBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SLS.Desktop.SLSDesktopServiceProxy.BookNotFoundFault), Action="http://tempuri.org/ISLSDesktopService/GetBookBookNotFoundFaultFault", Name="BookNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/SLS.WCFService")]
        SLS.Desktop.SLSDesktopServiceProxy.Book GetBook(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSDesktopService/GetAllBooks", ReplyAction="http://tempuri.org/ISLSDesktopService/GetAllBooksResponse")]
        SLS.Desktop.SLSDesktopServiceProxy.Book[] GetAllBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSDesktopService/GetDueBooks", ReplyAction="http://tempuri.org/ISLSDesktopService/GetDueBooksResponse")]
        SLS.Desktop.SLSDesktopServiceProxy.Book[] GetDueBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSDesktopService/AddAuthor", ReplyAction="http://tempuri.org/ISLSDesktopService/AddAuthorResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SLS.Desktop.SLSDesktopServiceProxy.EntityCouldNotBeAdded), Action="http://tempuri.org/ISLSDesktopService/AddAuthorEntityCouldNotBeAddedFault", Name="EntityCouldNotBeAdded", Namespace="http://schemas.datacontract.org/2004/07/SLS.WCFService")]
        bool AddAuthor(SLS.Desktop.SLSDesktopServiceProxy.author authorToAdd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLSDesktopService/AddBook", ReplyAction="http://tempuri.org/ISLSDesktopService/AddBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SLS.Desktop.SLSDesktopServiceProxy.EntityCouldNotBeAdded), Action="http://tempuri.org/ISLSDesktopService/AddBookEntityCouldNotBeAddedFault", Name="EntityCouldNotBeAdded", Namespace="http://schemas.datacontract.org/2004/07/SLS.WCFService")]
        bool AddBook(SLS.Desktop.SLSDesktopServiceProxy.book1 bookToAdd, SLS.Desktop.SLSDesktopServiceProxy.author[] authors);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISLSDesktopServiceChannel : SLS.Desktop.SLSDesktopServiceProxy.ISLSDesktopService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SLSDesktopServiceClient : System.ServiceModel.ClientBase<SLS.Desktop.SLSDesktopServiceProxy.ISLSDesktopService>, SLS.Desktop.SLSDesktopServiceProxy.ISLSDesktopService {
        
        public SLSDesktopServiceClient() {
        }
        
        public SLSDesktopServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SLSDesktopServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLSDesktopServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLSDesktopServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SLS.Desktop.SLSDesktopServiceProxy.Book GetBook(int bookId) {
            return base.Channel.GetBook(bookId);
        }
        
        public SLS.Desktop.SLSDesktopServiceProxy.Book[] GetAllBooks() {
            return base.Channel.GetAllBooks();
        }
        
        public SLS.Desktop.SLSDesktopServiceProxy.Book[] GetDueBooks() {
            return base.Channel.GetDueBooks();
        }
        
        public bool AddAuthor(SLS.Desktop.SLSDesktopServiceProxy.author authorToAdd) {
            return base.Channel.AddAuthor(authorToAdd);
        }
        
        public bool AddBook(SLS.Desktop.SLSDesktopServiceProxy.book1 bookToAdd, SLS.Desktop.SLSDesktopServiceProxy.author[] authors) {
            return base.Channel.AddBook(bookToAdd, authors);
        }
    }
}
