//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLS.WCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class author
    {
        public author()
        {
            this.book_authors = new HashSet<book_authors>();
        }
    
        public int id { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public Nullable<System.DateTime> date_of_death { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<book_authors> book_authors { get; set; }
    }
}
