//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLS.WCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public book()
        {
            this.book_authors = new HashSet<book_authors>();
            this.borrows = new HashSet<borrow>();
            this.reservations = new HashSet<reservation>();
            this.categories = new HashSet<category>();
        }
    
        public int id { get; set; }
        public string isbn { get; set; }
        public Nullable<int> publisher_id_fk { get; set; }
        public Nullable<System.DateTime> publish_date { get; set; }
        public string publish_city { get; set; }
        public Nullable<int> publish_edition { get; set; }
        public string title { get; set; }
        public string cover { get; set; }
        public string table_of_contents { get; set; }
        public string language { get; set; }
        public string description { get; set; }
        public int available_copies { get; set; }
    
        public virtual ICollection<book_authors> book_authors { get; set; }
        public virtual publisher publisher { get; set; }
        public virtual ICollection<borrow> borrows { get; set; }
        public virtual ICollection<reservation> reservations { get; set; }
        public virtual ICollection<category> categories { get; set; }
    }
}
