//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLS.WCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_authors
    {
        public int book_id_fk { get; set; }
        public int author_id_fk { get; set; }
        public int ord { get; set; }
    
        public virtual author author { get; set; }
        public virtual book book { get; set; }
    }
}
