//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLS.WCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int id { get; set; }
        public int book_id_fk { get; set; }
        public int user_id_fk { get; set; }
        public System.DateTime reservation_date { get; set; }
        public Nullable<int> queue_position { get; set; }
    
        public virtual book book { get; set; }
        public virtual user user { get; set; }
    }
}
