//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLS.WCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.borrows = new HashSet<borrow>();
            this.reservations = new HashSet<reservation>();
        }
    
        public int id { get; set; }
        public int role_id_fk { get; set; }
        public string login { get; set; }
        public string email { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public int phone { get; set; }
        public string passwd { get; set; }
        public int incorrect_login_cnt { get; set; }
        public string last_login_info { get; set; }
        public string token { get; set; }
    
        public virtual ICollection<borrow> borrows { get; set; }
        public virtual ICollection<reservation> reservations { get; set; }
        public virtual role role { get; set; }
    }
}
